name: GitHub Actions Demo

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '15 6 * * 0'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger event and branch name
        run: |
          echo "Triggering event: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: List all files
        run: |
          echo "${{ github.repository }} files:"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - name: Output
        run: |
          echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - name: Output
        run: |
          echo "Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: 
      - 'Test'
      - 'Load-Test'
    if: github.event.inputs.environment == 'Production'
    environment: 
      name: Production
      url: https://writeabout.net
    steps:
      - name: Step 1
        run: |
          echo "Step 1..."
          sleep 10
      - name: Step 2
        run: |
          echo "Step 2..."
          sleep 10
      - name: Step 3
        run: |
          echo "Step 3..."
          sleep 10
      - name: Step 4
        run: |
          echo "Step 4..."
          sleep 10
      - name: Step 5
        run: |
          echo "Step 5..."
          sleep 10
    
