name: GitHub Actions Demo

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.github/**'
  schedule:
    - cron: '15 6 * * 0'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger event and branch name
        run: |
          echo "Triggering event: ${{ github.event_name }}"
          echo "Branch name: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: List all files
        run: |
          echo "${{ github.repository }} files:"
          tree
